version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gen_api
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-4000}"
    environment:
      PORT: ${PORT:-4000}
      ENV: ${ENV:-development}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@postgres:5432/gen}
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: gen_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-gen}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
