services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: audiogen_api
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-4000}"
    environment:
      PORT: ${PORT:-4000}
      ENV: ${ENV:-development}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@postgres:5432/audiogen}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      S3_ENDPOINT: ${S3_ENDPOINT:-http://minio:9000}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
      S3_BUCKET: ${S3_BUCKET:-audiogen-artifacts}
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
      - minio

  postgres:
    image: postgres:16-alpine
    container_name: audiogen_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-audiogen}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: audiogen_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  minio:
    image: quay.io/minio/minio:latest
    container_name: audiogen_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - minio-data:/data
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9000/minio/health/live",
        ]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: audiogen_worker
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      RQ_QUEUES: ${RQ_QUEUES:-audio,default}
      S3_ENDPOINT: ${S3_ENDPOINT:-http://minio:9000}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
      S3_BUCKET: ${S3_BUCKET:-audiogen-artifacts}
    depends_on:
      - redis
      - minio
    command: sh -c "python -m worker.worker"

volumes:
  postgres-data:
  redis-data:
  minio-data:
