apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: gen
labels:
  app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/gen-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: gen
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
