apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: audiogen
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: audiogen
labels:
  app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: audiogen
            - name: POSTGRES_USER
              value: audiogen
            - name: POSTGRES_PASSWORD
              value: audiogen
          ports:
            - containerPort: 5432
