apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: gen
labels:
  app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/your-org/gen-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV
              value: "k8s"
